server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1306adf
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.zhangaochong.data_transport_demo.dao
  mapper-locations: classpath:mapper/*.xml

data-transport:
  backup-table-postfix: _bak
  multi-datasource:
    datasource1:
      url: jdbc:mysql://localhost:3306/datasource1
      username: root
      password: 1306adf
      driver-class-name: com.mysql.cj.jdbc.Driver
    datasource2:
      url: jdbc:mysql://localhost:3306/datasource2
      username: root
      password: 1306adf
      driver-class-name: com.mysql.cj.jdbc.Driver

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    executor:
      appname: data-tansport-demo-jobhandler
      logpath: /tmp/applogs/xxl-job/data-tansport-demo-jobhandler
      port: 9999
      ip:
      address:
      logretentiondays: -1